In [ ]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None , description: str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
        if description != None :
            print(f" <-- {description} -->")
    print('type: ' , type(val))
    display(val , '\n')
    # return val


In [2]:
import numpy as np 
import pandas as pd

In [3]:
array = np.array([1,2,3,4])
pr(array)
pr(array*2)

type:  <class 'numpy.ndarray'>
[1 2 3 4] 

type:  <class 'numpy.ndarray'>
[2 4 6 8] 



In [4]:
test_array  = [1,2,3,4]
pr(test_array , 'python list')
pr(np.array(test_array) , 'numpy array')
pr(pd.Series(test_array) , 'pandas series')

 ---------------------- python list ---------------------- 
type:  <class 'list'>
[1, 2, 3, 4] 

 ---------------------- numpy array ---------------------- 
type:  <class 'numpy.ndarray'>
[1 2 3 4] 

 ---------------------- pandas series ---------------------- 
type:  <class 'pandas.core.series.Series'>
0    1
1    2
2    3
3    4
dtype: int64 



In [5]:
pr(array.size , 'array.size')
pr(array.shape , 'array.shape')
pr(array.ndim , 'array.ndim')
pr(array.dtype , 'array.dtype')
pr(array.itemsize , 'array.itemsize')
pr(array.nbytes , 'array.nbytes')

 ---------------------- array.size ---------------------- 
type:  <class 'int'>
4 

 ---------------------- array.shape ---------------------- 
type:  <class 'tuple'>
(4,) 

 ---------------------- array.ndim ---------------------- 
type:  <class 'int'>
1 

 ---------------------- array.dtype ---------------------- 
type:  <class 'numpy.dtypes.Int64DType'>
int64 

 ---------------------- array.itemsize ---------------------- 
type:  <class 'int'>
8 

 ---------------------- array.nbytes ---------------------- 
type:  <class 'int'>
32 



In [8]:
a = np.array([10,20,30,40])
b = a[1:3]
b[0] = 999
pr(a , 'a is changed when b changed') 
c = a[1:3].copy()
c[0] = 123
pr(a , 'a do not change when c change')

 ---------------------- a is changed when b changed ---------------------- 
type:  <class 'numpy.ndarray'>
[ 10 999  30  40] 

 ---------------------- a do not change when c change ---------------------- 
type:  <class 'numpy.ndarray'>
[ 10 999  30  40] 



In [ ]:
test_array = [1 ,2,3,4,5]
a = np.array(test_array , dtype=np.int64)
b = np.array(test_array , dtype=np.int32)
c = np.array(test_array , dtype=np.float32)
pr(a , 'a')
pr(b , 'b')
pr(c , 'c')