In [1]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None , description: str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
        if description != None :
            print(f" <-- {description} -->")
    print('type: ' , type(val))
    display(val)
    # return val


In [2]:
import numpy as np 
import pandas as pd

In [3]:
array = np.array([1,2,3,4])
pr(array)
pr(array*2)

type:  <class 'numpy.ndarray'>


array([1, 2, 3, 4])

type:  <class 'numpy.ndarray'>


array([2, 4, 6, 8])

In [4]:
test_array  = [1,2,3,4]
pr(test_array , 'python list')
pr(np.array(test_array) , 'numpy array')
pr(pd.Series(test_array) , 'pandas series')

 ---------------------- python list ---------------------- 
type:  <class 'list'>


[1, 2, 3, 4]

 ---------------------- numpy array ---------------------- 
type:  <class 'numpy.ndarray'>


array([1, 2, 3, 4])

 ---------------------- pandas series ---------------------- 
type:  <class 'pandas.core.series.Series'>


0    1
1    2
2    3
3    4
dtype: int64

In [5]:
pr(array.size , 'array.size')
pr(array.shape , 'array.shape')
pr(array.ndim , 'array.ndim')
pr(array.dtype , 'array.dtype')
pr(array.itemsize , 'array.itemsize')
pr(array.nbytes , 'array.nbytes')

 ---------------------- array.size ---------------------- 
type:  <class 'int'>


4

 ---------------------- array.shape ---------------------- 
type:  <class 'tuple'>


(4,)

 ---------------------- array.ndim ---------------------- 
type:  <class 'int'>


1

 ---------------------- array.dtype ---------------------- 
type:  <class 'numpy.dtypes.Int64DType'>


dtype('int64')

 ---------------------- array.itemsize ---------------------- 
type:  <class 'int'>


8

 ---------------------- array.nbytes ---------------------- 
type:  <class 'int'>


32

In [6]:
a = np.array([10,20,30,40])
b = a[1:3]
b[0] = 999
pr(a , 'a is changed when b changed') 
c = a[1:3].copy()
c[0] = 123
pr(a , 'a do not change when c change')

 ---------------------- a is changed when b changed ---------------------- 
type:  <class 'numpy.ndarray'>


array([ 10, 999,  30,  40])

 ---------------------- a do not change when c change ---------------------- 
type:  <class 'numpy.ndarray'>


array([ 10, 999,  30,  40])

In [7]:
test_array = [1 ,2,3,4,5]
a = np.array(test_array , dtype=np.int64)
b = np.array(test_array , dtype=np.int32)
c = np.array(test_array , dtype=np.float32)
pr(a.dtype , 'a')
pr(b.dtype , 'b')
pr(c.dtype , 'c')
pr(a.astype(np.float64).dtype , 'type cast int to float')

 ---------------------- a ---------------------- 
type:  <class 'numpy.dtypes.Int64DType'>


dtype('int64')

 ---------------------- b ---------------------- 
type:  <class 'numpy.dtypes.Int32DType'>


dtype('int32')

 ---------------------- c ---------------------- 
type:  <class 'numpy.dtypes.Float32DType'>


dtype('float32')

 ---------------------- type cast int to float ---------------------- 
type:  <class 'numpy.dtypes.Float64DType'>


dtype('float64')

# multidimensional arrays

In [8]:
array0D = np.array('A')
array1D = np.array(['A','B', 'C'])
array2D = np.array([['A','B', 'C'] , ['D','E','F'] , ['G','H','J']])
array3D = np.array([[['A','B', 'C'] , ['D','E','F'] , ['G','H','J']],
                    [['K','L', 'M'] , ['N','O','P'] , ['Q','R','S']],
                    [['T','U', 'V'] , ['W','X','Z'] , ['G','H','J']],])
pr(array0D.ndim , 'array0D.ndim' )
pr(array0D.shape , 'array0D.shape' )
pr(array1D.ndim , 'array1D.ndim' )
pr(array1D.shape , 'array1D.shape' )
pr(array2D.ndim , 'array2D.ndim' )
pr(array2D.shape , 'array2D.shape' )
pr(array3D.ndim , 'array3D.ndim' )
pr(array3D.shape , 'array3D.shape' )

 ---------------------- array0D.ndim ---------------------- 
type:  <class 'int'>


0

 ---------------------- array0D.shape ---------------------- 
type:  <class 'tuple'>


()

 ---------------------- array1D.ndim ---------------------- 
type:  <class 'int'>


1

 ---------------------- array1D.shape ---------------------- 
type:  <class 'tuple'>


(3,)

 ---------------------- array2D.ndim ---------------------- 
type:  <class 'int'>


2

 ---------------------- array2D.shape ---------------------- 
type:  <class 'tuple'>


(3, 3)

 ---------------------- array3D.ndim ---------------------- 
type:  <class 'int'>


3

 ---------------------- array3D.shape ---------------------- 
type:  <class 'tuple'>


(3, 3, 3)

In [9]:
# chain indexing
pr(array3D[0][0][0])
# multidimensional indexing
pr(array3D[0,0,0])

type:  <class 'numpy.str_'>


np.str_('A')

type:  <class 'numpy.str_'>


np.str_('A')

In [10]:
pr(array3D , 'array3D')
pr(array3D[0,2,1] + array3D[0,1,1] + array3D[1,0,1] + array3D[1,0,1] + array3D[1,1,1])

 ---------------------- array3D ---------------------- 
type:  <class 'numpy.ndarray'>


array([[['A', 'B', 'C'],
        ['D', 'E', 'F'],
        ['G', 'H', 'J']],

       [['K', 'L', 'M'],
        ['N', 'O', 'P'],
        ['Q', 'R', 'S']],

       [['T', 'U', 'V'],
        ['W', 'X', 'Z'],
        ['G', 'H', 'J']]], dtype='<U1')

type:  <class 'str'>


'HELLO'

In [11]:
x = np.arange(24)
x= x.reshape(2,3,4)
pr(x)

type:  <class 'numpy.ndarray'>


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [12]:
pr(np.zeros(shape=(3,3) , dtype=np.int64))
pr(np.ones(shape=(3,3) , dtype=np.float32))
pr(np.full(shape=(2,2) , fill_value=7 , dtype=np.float32))
pr(np.eye(5))
pr(np.arange(12).reshape(2,3,2))
pr(np.linspace(0,1,5))

type:  <class 'numpy.ndarray'>


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

type:  <class 'numpy.ndarray'>


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

type:  <class 'numpy.ndarray'>


array([[7., 7.],
       [7., 7.]], dtype=float32)

type:  <class 'numpy.ndarray'>


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

type:  <class 'numpy.ndarray'>


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

type:  <class 'numpy.ndarray'>


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# slicing ✂

In [13]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
pr(array , 'array')

 ---------------------- array ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
# the syntax for the indexing are array[start:end:index]
pr(array[0] , 'first element')
pr(array[-1] , 'last element')
pr(array[1,1] , 'second raw - second column')
pr(array[1,1:] , 'second raw - from second column to the end')
pr(array[1,1::2] , 'second raw - from second column to the end with step 2')

 ---------------------- first element ---------------------- 
type:  <class 'numpy.ndarray'>


array([1, 2, 3, 4])

 ---------------------- last element ---------------------- 
type:  <class 'numpy.ndarray'>


array([13, 14, 15, 16])

 ---------------------- second raw - second column ---------------------- 
type:  <class 'numpy.int64'>


np.int64(6)

 ---------------------- second raw - from second column to the end ---------------------- 
type:  <class 'numpy.ndarray'>


array([6, 7, 8])

 ---------------------- second raw - from second column to the end with step 2 ---------------------- 
type:  <class 'numpy.ndarray'>


array([6, 8])

In [15]:
pr(array[0:3] , 'this will give you from the first three rows because the end is exclusive')
pr(array[::2] , 'select all rows but the step = 2')

 ---------------------- this will give you from the first three rows because the end is exclusive ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

 ---------------------- select all rows but the step = 2 ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [16]:
pr(array[::-1 , ::-1] , 'return all the rows reversed and the columns is reversed too')

 ---------------------- return all the rows reversed and the columns is reversed too ---------------------- 
type:  <class 'numpy.ndarray'>


array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [17]:
pr(array[:,0] , 'select the first column from all rows')

 ---------------------- select the first column from all rows ---------------------- 
type:  <class 'numpy.ndarray'>


array([ 1,  5,  9, 13])

In [18]:
pr(array[:,-1] , 'select the last column from all rows')

 ---------------------- select the last column from all rows ---------------------- 
type:  <class 'numpy.ndarray'>


array([ 4,  8, 12, 16])

In [19]:
pr(array[0:3,0:3] , 'note the end is exclusive and the start is inclusive')

 ---------------------- note the end is exclusive and the start is inclusive ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [20]:
pr(array[::2,::2] , 'the step is two for both the rows and columns')

 ---------------------- the step is two for both the rows and columns ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 1,  3],
       [ 9, 11]])

In [21]:
a = np.arange(5 , dtype=np.int64)
pr(a , 'a')
pr(a.shape , 'a.shape')
pr(a.strides , 'a.strides')

 ---------------------- a ---------------------- 
type:  <class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

 ---------------------- a.shape ---------------------- 
type:  <class 'tuple'>


(5,)

 ---------------------- a.strides ---------------------- 
type:  <class 'tuple'>


(8,)

In [22]:
m = np.arange(12 , dtype=np.int64).reshape((3,4))
pr(m , 'm')
pr(m.dtype.itemsize , 'm.dtype.itemsize')
pr(m.shape , 'm.shape')
pr(m.strides , 'm.strides')

 ---------------------- m ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

 ---------------------- m.dtype.itemsize ---------------------- 
type:  <class 'int'>


8

 ---------------------- m.shape ---------------------- 
type:  <class 'tuple'>


(3, 4)

 ---------------------- m.strides ---------------------- 
type:  <class 'tuple'>


(32, 8)

In [23]:
pr(m , 'm')
col1 = m[: , 1]
pr(col1 , 'col1')
pr(col1.strides , 'col1.strides')
row1 = m[1,:]
pr(row1 , 'row1')
pr(row1.strides , 'row1.strides')

 ---------------------- m ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

 ---------------------- col1 ---------------------- 
type:  <class 'numpy.ndarray'>


array([1, 5, 9])

 ---------------------- col1.strides ---------------------- 
type:  <class 'tuple'>


(32,)

 ---------------------- row1 ---------------------- 
type:  <class 'numpy.ndarray'>


array([4, 5, 6, 7])

 ---------------------- row1.strides ---------------------- 
type:  <class 'tuple'>


(8,)

In [24]:
mr = m[::-1 , ::-1]
pr(mr , 'mr')
pr(mr.strides , 'mr.strides')

 ---------------------- mr ---------------------- 
type:  <class 'numpy.ndarray'>


array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

 ---------------------- mr.strides ---------------------- 
type:  <class 'tuple'>


(-32, -8)

In [25]:
a1 = np.arange(0,10 , dtype=np.int64)
pr(a1 , 'a1')
pr(a1[np.array([0,2,4])] , 'new array not a view')
pr(a1[[0,2,4]] , 'new array not a view')

 ---------------------- a1 ---------------------- 
type:  <class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 ---------------------- new array not a view ---------------------- 
type:  <class 'numpy.ndarray'>


array([0, 2, 4])

 ---------------------- new array not a view ---------------------- 
type:  <class 'numpy.ndarray'>


array([0, 2, 4])

In [26]:
a1 = np.arange(1,7).reshape(3,2)
pr(a1)
a2 = a1[[0,1,2] , [0,0,1]]
pr(a2 , 'a2')

type:  <class 'numpy.ndarray'>


array([[1, 2],
       [3, 4],
       [5, 6]])

 ---------------------- a2 ---------------------- 
type:  <class 'numpy.ndarray'>


array([1, 3, 6])

In [27]:
a1 = np.arange(15).reshape((3,5))
pr(a1 , 'a1')
a2 = a1[[2,0,1] , [1,0,2]]
pr(a2)

 ---------------------- a1 ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

type:  <class 'numpy.ndarray'>


array([11,  0,  7])

In [28]:
a = np.arange(10)
pr(a , 'a')
pr(a[a % 2 == 0])
pr(a[a % 2 == 0] ** 2)
pr(a[a >5])
pr(a[a==5])

 ---------------------- a ---------------------- 
type:  <class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

type:  <class 'numpy.ndarray'>


array([0, 2, 4, 6, 8])

type:  <class 'numpy.ndarray'>


array([ 0,  4, 16, 36, 64])

type:  <class 'numpy.ndarray'>


array([6, 7, 8, 9])

type:  <class 'numpy.ndarray'>


array([5])

In [29]:
a =  np.arange(10)
pr(a , 'a')
pr(a % 2 == 0 , 'mask')

 ---------------------- a ---------------------- 
type:  <class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 ---------------------- mask ---------------------- 
type:  <class 'numpy.ndarray'>


array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

# Arithmetic

In [36]:
# scalar arithmetic 
array = np.arange(12).reshape((4,3))
pr(array , 'array')
pr(array + 1  , 'array + 1 ')
pr(array * 2  , 'array * 2 ')
pr(array / 2  , 'array / 2 ')
pr(array ** 2  , 'array ** 2 ')


 ---------------------- array ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

 ---------------------- array + 1  ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

 ---------------------- array * 2  ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

 ---------------------- array / 2  ---------------------- 
type:  <class 'numpy.ndarray'>


array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

 ---------------------- array ** 2  ---------------------- 
type:  <class 'numpy.ndarray'>


array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [44]:
# vectorized math functions
array = np.arange(12).reshape((4,3))
pr(array , 'array')
pr(array * np.array([1,2,3]) , 'vectorized operation')
# the line of code below throws an error because the shape don't match.
# pr(array * np.array([1,2,3,4]))
pr(np.sqrt(array) , 'built in square root vectorized function')
pr(np.square(array) , 'built in square vectorized function')
pr(np.round(array * 1.2) , 'example on round function')
pr(np.ceil(array * 1.2) , 'example on ceil function')

 ---------------------- array ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

 ---------------------- vectorized operation ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24],
       [ 9, 20, 33]])

 ---------------------- built in square root vectorized function ---------------------- 
type:  <class 'numpy.ndarray'>


array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

 ---------------------- built in square vectorized function ---------------------- 
type:  <class 'numpy.ndarray'>


array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

 ---------------------- example on round function ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 0.,  1.,  2.],
       [ 4.,  5.,  6.],
       [ 7.,  8., 10.],
       [11., 12., 13.]])

 ---------------------- example on ceil function ---------------------- 
type:  <class 'numpy.ndarray'>


array([[ 0.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 8.,  9., 10.],
       [11., 12., 14.]])

In [45]:
# built in constants
pr(np.pi , 'pi')

 ---------------------- pi ---------------------- 
type:  <class 'float'>


3.141592653589793

In [50]:
# element wise operations
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
pr(array1+array2)
pr(array1-array2)
pr(array1*array2)
pr(array1/array2)
pr(array1**array2)

type:  <class 'numpy.ndarray'>


array([5, 7, 9])

type:  <class 'numpy.ndarray'>


array([-3, -3, -3])

type:  <class 'numpy.ndarray'>


array([ 4, 10, 18])

type:  <class 'numpy.ndarray'>


array([0.25, 0.4 , 0.5 ])

type:  <class 'numpy.ndarray'>


array([  1,  32, 729])

In [54]:
# comparison operators
scores = np.array([40,38 , 90 , 100 ,73  , 67])
pr(scores == 100)
pr(scores >= 60)
pr(scores<60)
scores[scores < 60] = 0
pr(scores)

type:  <class 'numpy.ndarray'>


array([False, False, False,  True, False, False])

type:  <class 'numpy.ndarray'>


array([False, False,  True,  True,  True,  True])

type:  <class 'numpy.ndarray'>


array([ True,  True, False, False, False, False])

type:  <class 'numpy.ndarray'>


array([  0,   0,  90, 100,  73,  67])

# broadcasting
- broadcasting allows NumPy to perform operations on arrays with different shapes by virtually expanding dimensions so they match the larger array's shape.
- the main condition to remember is `the dimensions have the same size or one of the dimensions has a size 1`

In [56]:
array1 = np.array([[1,2,3,4]]) # size (1,4)
array2 = np.array([[1] , [2] , [3] , [4]]) # size (4,1)
pr(array1.shape , 'array1.shape')
pr(array2.shape , 'array2.shape')
pr(array1+array2) 

 ---------------------- array1.shape ---------------------- 
type:  <class 'tuple'>


(1, 4)

 ---------------------- array2.shape ---------------------- 
type:  <class 'tuple'>


(4, 1)

type:  <class 'numpy.ndarray'>


array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [57]:
# let's create a multiplication table
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],])
pr(array1*array2)

type:  <class 'numpy.ndarray'>


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])