In [ ]:
from typing import TypeVar


T = TypeVar('T')

def pr(val : T , title:str|None = None , description: str|None = None) : # type: ignore
    if title != None :
        print(f" ---------------------- {title} ---------------------- ")
        if description != None :
            print(f" <-- {description} -->")
    print('type: ' , type(val))
    display(val , '\n')
    # return val


In [2]:
import numpy as np 
import pandas as pd

In [3]:
array = np.array([1,2,3,4])
pr(array)
pr(array*2)

type:  <class 'numpy.ndarray'>
[1 2 3 4] 

type:  <class 'numpy.ndarray'>
[2 4 6 8] 



In [4]:
test_array  = [1,2,3,4]
pr(test_array , 'python list')
pr(np.array(test_array) , 'numpy array')
pr(pd.Series(test_array) , 'pandas series')

 ---------------------- python list ---------------------- 
type:  <class 'list'>
[1, 2, 3, 4] 

 ---------------------- numpy array ---------------------- 
type:  <class 'numpy.ndarray'>
[1 2 3 4] 

 ---------------------- pandas series ---------------------- 
type:  <class 'pandas.core.series.Series'>
0    1
1    2
2    3
3    4
dtype: int64 



In [5]:
pr(array.size , 'array.size')
pr(array.shape , 'array.shape')
pr(array.ndim , 'array.ndim')
pr(array.dtype , 'array.dtype')
pr(array.itemsize , 'array.itemsize')
pr(array.nbytes , 'array.nbytes')

 ---------------------- array.size ---------------------- 
type:  <class 'int'>
4 

 ---------------------- array.shape ---------------------- 
type:  <class 'tuple'>
(4,) 

 ---------------------- array.ndim ---------------------- 
type:  <class 'int'>
1 

 ---------------------- array.dtype ---------------------- 
type:  <class 'numpy.dtypes.Int64DType'>
int64 

 ---------------------- array.itemsize ---------------------- 
type:  <class 'int'>
8 

 ---------------------- array.nbytes ---------------------- 
type:  <class 'int'>
32 



In [8]:
a = np.array([10,20,30,40])
b = a[1:3]
b[0] = 999
pr(a , 'a is changed when b changed') 
c = a[1:3].copy()
c[0] = 123
pr(a , 'a do not change when c change')

 ---------------------- a is changed when b changed ---------------------- 
type:  <class 'numpy.ndarray'>
[ 10 999  30  40] 

 ---------------------- a do not change when c change ---------------------- 
type:  <class 'numpy.ndarray'>
[ 10 999  30  40] 



In [11]:
test_array = [1 ,2,3,4,5]
a = np.array(test_array , dtype=np.int64)
b = np.array(test_array , dtype=np.int32)
c = np.array(test_array , dtype=np.float32)
pr(a.dtype , 'a')
pr(b.dtype , 'b')
pr(c.dtype , 'c')
pr(a.astype(np.float64).dtype , 'type cast int to float')

 ---------------------- a ---------------------- 
type:  <class 'numpy.dtypes.Int64DType'>
int64 

 ---------------------- b ---------------------- 
type:  <class 'numpy.dtypes.Int32DType'>
int32 

 ---------------------- c ---------------------- 
type:  <class 'numpy.dtypes.Float32DType'>
float32 

 ---------------------- type cast int to float ---------------------- 
type:  <class 'numpy.dtypes.Float64DType'>
float64 



# multidimensional arrays

In [15]:
array0D = np.array('A')
array1D = np.array(['A','B', 'C'])
array2D = np.array([['A','B', 'C'] , ['D','E','F'] , ['G','H','J']])
array3D = np.array([[['A','B', 'C'] , ['D','E','F'] , ['G','H','J']],
                    [['K','L', 'M'] , ['N','O','P'] , ['Q','R','S']],
                    [['T','U', 'V'] , ['W','X','Z'] , ['G','H','J']],])
pr(array0D.ndim , 'array0D.ndim' )
pr(array0D.shape , 'array0D.shape' )
pr(array1D.ndim , 'array1D.ndim' )
pr(array1D.shape , 'array1D.shape' )
pr(array2D.ndim , 'array2D.ndim' )
pr(array2D.shape , 'array2D.shape' )
pr(array3D.ndim , 'array3D.ndim' )
pr(array3D.shape , 'array3D.shape' )

 ---------------------- array0D.ndim ---------------------- 
type:  <class 'int'>
0 

 ---------------------- array0D.shape ---------------------- 
type:  <class 'tuple'>
() 

 ---------------------- array1D.ndim ---------------------- 
type:  <class 'int'>
1 

 ---------------------- array1D.shape ---------------------- 
type:  <class 'tuple'>
(3,) 

 ---------------------- array2D.ndim ---------------------- 
type:  <class 'int'>
2 

 ---------------------- array2D.shape ---------------------- 
type:  <class 'tuple'>
(3, 3) 

 ---------------------- array3D.ndim ---------------------- 
type:  <class 'int'>
3 

 ---------------------- array3D.shape ---------------------- 
type:  <class 'tuple'>
(3, 3, 3) 



In [17]:
# chain indexing
pr(array3D[0][0][0])
# multidimensional indexing
pr(array3D[0,0,0])

type:  <class 'numpy.str_'>
A 

type:  <class 'numpy.str_'>
A 



In [23]:
pr(array3D , 'array3D')
pr(array3D[0,2,1] + array3D[0,1,1] + array3D[1,0,1] + array3D[1,0,1] + array3D[1,1,1])

 ---------------------- array3D ---------------------- 
type:  <class 'numpy.ndarray'>
[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'J']]

 [['K' 'L' 'M']
  ['N' 'O' 'P']
  ['Q' 'R' 'S']]

 [['T' 'U' 'V']
  ['W' 'X' 'Z']
  ['G' 'H' 'J']]] 

type:  <class 'str'>
HELLO 



In [27]:
x = np.arange(24)
x= x.reshape(2,3,4)
pr(x)

type:  <class 'numpy.ndarray'>
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 



In [37]:
pr(np.zeros(shape=(3,3) , dtype=np.int64))
pr(np.ones(shape=(3,3) , dtype=np.float32))
pr(np.full(shape=(2,2) , fill_value=7 , dtype=np.float32))
pr(np.eye(5))
pr(np.arange(12).reshape(2,3,2))
pr(np.linspace(0,1,5))

type:  <class 'numpy.ndarray'>
[[0 0 0]
 [0 0 0]
 [0 0 0]] 

type:  <class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

type:  <class 'numpy.ndarray'>
[[7. 7.]
 [7. 7.]] 

type:  <class 'numpy.ndarray'>
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

type:  <class 'numpy.ndarray'>
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 

type:  <class 'numpy.ndarray'>
[0.   0.25 0.5  0.75 1.  ] 

